name: TESTING

on:
  # Trigger the workflow on pull requests to master
  # job will only run if merge was successful
  pull_request:
    branches: 
      - master
    types: [ closed ]

jobs:
  changedFiles:
    if: github.event.pull_request.merged == false  # CHANGE TO TRUE!
    runs-on: ubuntu-latest

    # outputs:
    #   all: ${{ steps.changes.outputs.all }}
    #   lambda: ${{ steps.changes.outputs.lambda }}
    #   test: ${{ steps.changes.outputs.test }}
    #   sql: ${{ steps.changes.outputs.sql }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        run: |
          echo "${{ steps.files.outputs.all }}"
